### ISSUE TITLE
Unable to write regexp for WaitForNavigation

### ISSUE THREAD

**Issue by sagikazarmark** [playwright-community/playwright-go#125]
I'm trying to see if the page gets redirected to a URL that looks like `api-SOME_HASH.mywebsite.com`. Unfortunately, none of the URL options work.

Here is the code:

```go
	var timeout float64 = float64(10 * time.Second.Milliseconds())
	var url = `/mywebsite\.com/`
	_, err = page.WaitForNavigation(playwright.PageWaitForNavigationOptions{
		Timeout: &timeout,
		URL:     &url,
	})
```

The different options I tried for `url`:
- `"/mywebsite\.com/"`
- `"mywebsite\.com"`
- `"mywebsite.com"`
- `"*mywebsite.com*"`
- `".*mywebsite\.com.*"`
- `regexp.MustCompile(".*mywebsite\.com.*")`

(Note: quotes must be substituted with backticks because of escaping)

All of the above result in the following error:

```
panic: (*string) 0xc0004049f0

goroutine 34 [running]:
github.com/mxschmitt/playwright-go.(*urlMatcher).Matches(0xc000404a00, 0xc00046e000, 0x276, 0x3)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/helpers.go:198 +0x3fc
github.com/mxschmitt/playwright-go.(*frameImpl).WaitForNavigation.func1(0xc000439fc0, 0x1, 0x1, 0x0)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/frame.go:165 +0x10e
reflect.Value.call(0x1413a60, 0xc000404a10, 0x13, 0x14afcbd, 0x4, 0xc00028b8f0, 0x1, 0x1, 0x18, 0xc000464720, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x1413a60, 0xc000404a10, 0x13, 0xc0001c9458, 0x1, 0x1, 0x14060a0, 0x1, 0xc000464720)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/mxschmitt/playwright-go.waitForEvent.func1(0xc000439f60, 0x1, 0x1)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/helpers.go:314 +0x206
reflect.Value.call(0x140b500, 0xc000406ed0, 0x13, 0x14afcbd, 0x4, 0xc00028b8a8, 0x1, 0x1, 0x14ae2e0, 0xc0001c9750, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x140b500, 0xc000406ed0, 0x13, 0xc00028b878, 0x1, 0x1, 0xc00028b878, 0xc0001c9810, 0x0)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/mxschmitt/playwright-go.(*eventEmitter).Emit.func1(0xc000404a40, 0x1, 0x1)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/event_emitter.go:38 +0x1a5
github.com/mxschmitt/playwright-go.(*eventEmitter).Emit(0xc0001d38d8, 0x14b1d1f, 0x9, 0xc0001c98d8, 0x1, 0x1)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/event_emitter.go:42 +0x252
github.com/mxschmitt/playwright-go.(*frameImpl).onFrameNavigated(0xc0001d38c0, 0xc000464690)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/frame.go:185 +0x191
reflect.Value.call(0x140b6c0, 0xc000191850, 0x13, 0x14afcbd, 0x4, 0xc00028b860, 0x1, 0x1, 0x14ae2e0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x140b6c0, 0xc000191850, 0x13, 0xc00028b860, 0x1, 0x1, 0xc00045ca70, 0x9, 0x1)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/mxschmitt/playwright-go.(*eventEmitter).Emit.func1(0xc000191860, 0x1, 0x1)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/event_emitter.go:38 +0x1a5
github.com/mxschmitt/playwright-go.(*eventEmitter).Emit(0xc00022f1f0, 0xc00045ca70, 0x9, 0xc0001c9dc0, 0x1, 0x1)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/event_emitter.go:42 +0x252
github.com/mxschmitt/playwright-go.(*connection).Dispatch(0xc00029a070, 0xc0002c1cc0)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/connection.go:73 +0x452
github.com/mxschmitt/playwright-go.(*transport).Start(0xc00028c0f0, 0x14d1740, 0xc0001acae0)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/transport.go:44 +0xc6
github.com/mxschmitt/playwright-go.(*connection).Start(...)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/connection.go:28
github.com/mxschmitt/playwright-go.Run.func1(0xc00029a070)
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/run.go:233 +0x32
created by github.com/mxschmitt/playwright-go.Run
	/Users/marksk/.local/share/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/run.go:232 +0x1d5
exit status 2
(node:16889) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:787:11)
    at Socket._write (net.js:799:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/protocol/transport.js:47:25)
    at DispatcherConnection.dispatcherConnection.onmessage (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/cli/driver.js:63:59)
    at DispatcherConnection.sendMessageToClient (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/dispatcher.js:136:14)
(node:16889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16889) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16889) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/protocol/transport.js:47:25)
    at DispatcherConnection.dispatcherConnection.onmessage (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/cli/driver.js:63:59)
    at DispatcherConnection.sendMessageToClient (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/dispatcher.js:136:14)
    at PageDispatcher._dispatchEvent (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/dispatcher.js:72:26)
    at Page.<anonymous> (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/pageDispatcher.js:64:71)
    at Page.emit (events.js:314:20)
    at FrameManager.requestFinished (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/server/frames.js:239:24)
(node:16889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16889) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/protocol/transport.js:47:25)
    at DispatcherConnection.dispatcherConnection.onmessage (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/cli/driver.js:63:59)
    at DispatcherConnection.sendMessageToClient (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/dispatcher.js:136:14)
    at new Dispatcher (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/dispatcher.js:63:30)
    at new RequestDispatcher (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/networkDispatchers.js:32:9)
    at Function.from (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/networkDispatchers.js:25:26)
    at Page.<anonymous> (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/pageDispatcher.js:58:137)
(node:16889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:16889) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed                                
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/protocol/transport.js:47:25)
    at DispatcherConnection.dispatcherConnection.onmessage (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/cli/driver.js:63:59)
    at DispatcherConnection.sendMessageToClient (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/dispatcher.js:136:14)
    at new Dispatcher (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/dispatcher.js:63:30)
    at new RequestDispatcher (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/networkDispatchers.js:32:9)
    at Function.from (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/networkDispatchers.js:25:26)
    at Page.<anonymous> (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/pageDispatcher.js:58:137)
(node:16889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:16889) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Transport.send (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/protocol/transport.js:47:25)
    at DispatcherConnection.dispatcherConnection.onmessage (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/cli/driver.js:63:59)
    at DispatcherConnection.sendMessageToClient (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/dispatcher.js:136:14)
    at new Dispatcher (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/dispatcher.js:63:30)
    at new RequestDispatcher (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/networkDispatchers.js:32:9)
    at Function.from (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/networkDispatchers.js:25:26)
    at Page.<anonymous> (/Users/marksk/Library/Caches/ms-playwright-go/1.10.0/package/lib/dispatchers/pageDispatcher.js:58:137)
(node:16889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

Am I doing something wrong? I would like to add here that I couldn't find any examples for URLs neither in the official playwright docs nor in playwright-go examples.

**Comment by ninadingole** [comment]
I tried to reproduce this issue with a test but didn't get any issues as @sagikazarmark reported. 

```
page, err := browser.NewPage()
	assert.NoError(t, err, "failed to create page")

	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()

		navigation, err := page.WaitForNavigation(playwright.PageWaitForNavigationOptions{
			Timeout: playwright.Float(3000),
			URL:     "https://todomvc.com/*",
		})

		assert.NoError(t, err, "failed to wait for navigation")
		assert.Equal(t, "https://todomvc.com/examples/react/", navigation.URL())

	}()

	_, err = page.Goto("https://todomvc.com/examples/react/#/")
	assert.NoError(t, err, "failed to navigate to page")

	wg.Wait()
```
