### ISSUE TITLE
response.Body() fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by qwenode** [playwright-community/playwright-go#306]
error log
```
<< 200 https://www.google.com/
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/playwright-community/playwright-go.(*connection).SendMessageToServer(0xc000158070, {0xc0000aa540, 0x26}, {0x3e5628, 0x4}, {0x3a8e80, 0xc00007fe30})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/connection.go:169 +0x56c
github.com/playwright-community/playwright-go.(*channel).innerSend(0xc0000b2310, {0x3e5628, 0x4}, 0x0, {0xc00011de90?, 0x0?, 0x0?})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/channel.go:26 +0x92
github.com/playwright-community/playwright-go.(*channel).Send(...)
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/channel.go:17
github.com/playwright-community/playwright-go.(*frameImpl).Goto(0xc0002119e0, {0x3eb83f, 0x17}, {0xc000008768, 0x1, 0x1})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/frame.go:73 +0x13c
github.com/playwright-community/playwright-go.(*pageImpl).Goto(0xc0000ae000?, {0x3eb83f?, 0x1?}, {0xc000008768?, 0x40fce8?, 0xc000056000?})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/page.go:180 +0x35
main.main()
        C:/data/www/testchromedriver/cmd/text/main.go:30 +0x1d7

goroutine 6 [chan receive]:
github.com/playwright-community/playwright-go.(*connection).SendMessageToServer(0xc000158070, {0xc0000aa8d0, 0x29}, {0x3e55c8, 0x4}, {0x3a8e80, 0xc00025cff0})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/connection.go:169 +0x56c
github.com/playwright-community/playwright-go.(*channel).innerSend(0xc0000b2460, {0x3e55c8, 0x4}, 0x0, {0x0?, 0xc000102c68?, 0x2?})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/channel.go:26 +0x92
github.com/playwright-community/playwright-go.(*channel).Send(...)
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/channel.go:17
github.com/playwright-community/playwright-go.(*responseImpl).Body(0xc0000b0ea0?)
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/response.go:41 +0x37
github.com/playwright-community/playwright-go.(*responseImpl).Text(0x446980?)
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/response.go:49 +0x19
main.main.func1({0x448498, 0xc00009a180})
        C:/data/www/testchromedriver/cmd/text/main.go:27 +0xfe
reflect.Value.call({0x3999c0?, 0x40fce8?, 0x110?}, {0x3e5508, 0x4}, {0xc0000923c0, 0x1, 0x0?})
        C:/data/env/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0x3999c0?, 0x40fce8?, 0x3ff0000000000000?}, {0xc0000923c0?, 0x21b854?, 0x18?})
        C:/data/env/go/src/reflect/value.go:368 +0xbc
github.com/playwright-community/playwright-go.(*eventEmitter).Emit.func1({0xc00018c5b0?, 0x1, 0x3e64be?})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/event_emitter.go:38 +0x1d1
github.com/playwright-community/playwright-go.(*eventEmitter).Emit(0xc0000a0178, {0x3e64be, 0x8}, {0xc000103540, 0x1, 0xc0001035b0?})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/event_emitter.go:42 +0x1c6
github.com/playwright-community/playwright-go.newBrowserContext.func5(0x0?)
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/browser_context.go:413 +0x176
reflect.Value.call({0x399a40?, 0xc000258960?, 0x3a8a60?}, {0x3e5508, 0x4}, {0xc0000923a8, 0x1, 0x0?})
        C:/data/env/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0x399a40?, 0xc000258960?, 0x3ff0000000000000?}, {0xc0000923a8?, 0x1e2017?, 0x18?})
        C:/data/env/go/src/reflect/value.go:368 +0xbc
github.com/playwright-community/playwright-go.(*eventEmitter).Emit.func1({0xc000258970?, 0x1, 0xc00024b220?})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/event_emitter.go:38 +0x1d1
github.com/playwright-community/playwright-go.(*eventEmitter).Emit(0xc0000b22a0, {0xc00024b220, 0x8}, {0xc000103e18, 0x1, 0xc00024b260?})
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/event_emitter.go:42 +0x1c6
github.com/playwright-community/playwright-go.(*connection).Dispatch(0xc000158070, 0xc0000906e0)
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/connection.go:79 +0x531
github.com/playwright-community/playwright-go.(*pipeTransport).Start(0xc00007f050)
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/transport.go:45 +0x1b3
github.com/playwright-community/playwright-go.(*PlaywrightDriver).run.func1()
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/run.go:180 +0x1d
created by github.com/playwright-community/playwright-go.(*PlaywrightDriver).run
        C:/data/env/gopath/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/run.go:179 +0x256

```

here is the code

```
package main

import (
	"fmt"
	"github.com/playwright-community/playwright-go"
	"log"
)

func main() {
	pw, err := playwright.Run()
	if err != nil {
		log.Fatalf("could not launch playwright: %v", err)
	}
	browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
		Headless: playwright.Bool(false),
	})
	if err != nil {
		log.Fatalf("could not launch Chromium: %v", err)
	}
	page, err := browser.NewPage()
	if err != nil {
		log.Fatalf("could not create page: %v", err)
	}
	
	page.On("response", func(response playwright.Response) {
		fmt.Printf("<< %v %s\n", response.Status(), response.URL())
		log.Println(response.Text())
		
	})
	if _, err = page.Goto("https://www.google.com/", playwright.PageGotoOptions{
		WaitUntil: playwright.WaitUntilStateNetworkidle,
	}); err != nil {
		log.Fatalf("could not goto: %v", err)
	}
	select {}
	
}
```

**Comment by ninadingole** [comment]
I ran the same code on my mac and it worked without any deadlock. What version of golang are you using?

**Comment by wilobs** [comment]
I'm not being able to capture the Response Body, Text, JSON of network calls.
``` go 
page.On("response", func(response playwright.Response) {
    fmt.Printf("<< %v %s\n", response.Status(), response.URL())
		
     textBody, err := response.Text()  // << Here it freezes the rest of the execution of the test
     if err != nil {
        log.Println(err)
     }           
     log.Println(response.Text())
		
     // More code not being executed

})
```
Also, i've tried with `reponse.Finished()`, none of those approaches worked for me.
Even with **"requestfinished"** event when calling the `response, err := request.Response()`.

Is there any channel usage or anything else that I'm missing out? Thanks

**Comment by roimee6** [comment]
Same

**Comment by ariefsn** [comment]
facing this issue too.
any idea how to solve?
Go 1.23.0
