### ISSUE TITLE
Playwright-go randomly hangs?

### ISSUE THREAD

**Issue by supercom32** [playwright-community/playwright-go#362]
Hi Everyone,

Maybe I'm alone on this, but I found that the latest playwright-go release seems to hang randomly once in a while for me. So if I have an app which is called, does some automation / work, then shuts down (maybe after an hour?), and is called again in a bash script loop continuously, sometimes everything locks up. 

When this happens, my go program doesn't move to the next statement (whatever that might be) and the browser window doesn't appear to be doing anything. In some cases, it isn't even visible anymore (crash perhaps?). Killing the firefox processes I found doesn't seem to make program execution continue, and eventually get a defunct playwright-go process which becomes a zombie. 

Is this something anyone else has experienced with the new build?

**Comment by supercom32** [comment]
Just another observation: When Node.js dies underneath Playwright-go, it usually just prints out an error to console like this:
```
 if (!value) throw new Error(message || 'Assertion error');
                    ^

Error: Assertion error
    at assert (/home/user/.cache/ms-playwright-go/1.35.1/package/lib/utils/debug.js:29:21)
    at FrameManager.frameAttached (/home/user/.cache/ms-playwright-go/1.35.1/package/lib/server/frames.js:104:25)
    at FFPage._onFrameAttached (/home/user/.cache/ms-playwright-go/1.35.1/package/lib/server/firefox/ffPage.js:175:30)
    at FFSession.emit (node:events:513:28)
    at /home/user/.cache/ms-playwright-go/1.35.1/package/lib/server/firefox/ffConnection.js:204:41

Node.js v18.16.0
```
After which, your go application just dies because it never gets control again (and ends up waiting for something forever?). Because this isn't easy to reproduce (Except to let your automation app run in a loop until it happens), I can't tell at which place we're locking up. 

Perhaps if tracking down the initial problem is too hard due to not having a reliable test case, maybe we could track down all the areas external calls to `playwright` are being made so we can detect deadlock states and just kill/throw a proper error when something happens? At least then, the user has recourse to deal with that error rather than having an app hang indefinitely.

**Comment by canstand** [comment]
There are indeed deadlock issues that are difficult to reproduce. Could you please test it with [this change](https://github.com/canstand/playwright-go/tree/dev)? The latest commit adds a client-side timeout for events with a timeout parameter.

**Comment by zouxingyuks** [comment]
panic: interface conversion: interface {} is nil, not string

goroutine 292 [running]:
github.com/playwright-community/playwright-go.(*frameImpl).Content(0xc000192b01?)
        D:/Document/GO/pkg/mod/github.com/playwright-community/playwright-go@v0.3500.0/frame.go:70 +0x5c
github.com/playwright-community/playwright-go.(*pageImpl).Content(0x1033570?)
        D:/Document/GO/pkg/mod/github.com/playwright-community/playwright-go@v0.3500.0/page.go:176 +0x28
pc_cnki_go/pc.(*testPage).Get(0xc00038c190, {0x102c868, 0xc00033a720}, 0xba5770?, 0xc000035020?)
        D:/Document/higheducation/exps/pc_cnki_go/pc/debug.go:88 +0x719
main.main.func1.2()
        D:/Document/higheducation/exps/pc_cnki_go/test.go:39 +0x69
created by main.main.func1
        D:/Document/higheducation/exps/pc_cnki_go/test.go:38 +0x34c
我在进行测试5分钟后出现此错误，但是前五分钟均是正常运行的，且内容成功获取

**Comment by gokaybiz** [comment]
> Just another observation: When Node.js dies underneath Playwright-go, it usually just prints out an error to console like this:
> 
> ```
>  if (!value) throw new Error(message || 'Assertion error');
>                     ^
> 
> Error: Assertion error
>     at assert (/home/user/.cache/ms-playwright-go/1.35.1/package/lib/utils/debug.js:29:21)
>     at FrameManager.frameAttached (/home/user/.cache/ms-playwright-go/1.35.1/package/lib/server/frames.js:104:25)
>     at FFPage._onFrameAttached (/home/user/.cache/ms-playwright-go/1.35.1/package/lib/server/firefox/ffPage.js:175:30)
>     at FFSession.emit (node:events:513:28)
>     at /home/user/.cache/ms-playwright-go/1.35.1/package/lib/server/firefox/ffConnection.js:204:41
> 
> Node.js v18.16.0
> ```
> 
> After which, your go application just dies because it never gets control again (and ends up waiting for something forever?). Because this isn't easy to reproduce (Except to let your automation app run in a loop until it happens), I can't tell at which place we're locking up.
> 
> Perhaps if tracking down the initial problem is too hard due to not having a reliable test case, maybe we could track down all the areas external calls to `playwright` are being made so we can detect deadlock states and just kill/throw a proper error when something takes too long? At least then, the user has recourse to deal with that error rather than having an app hang indefinitely. AFAIK, I think this has to be done on the `playwright-go` side, since the user has no control of this when calling the library.

Well, I'm writing because I think it's worth mentioning, I'm facing with exact same issue on latest official playwright (nodejs) library using firefox connection.
It just randomly stops, or kills entire application.
Also you can't reproduce it on purpose. So, something must be wrong with main logic-flow. Not golang port.

**Comment by mxschmitt** [comment]
Please re-open if you have a reproduction. Thank you.
