### ISSUE TITLE
[`could not send message` - `file already closed` - `could not decode json`] Playwright randomly crash after somes times.

### ISSUE THREAD

**Issue by 0xF7A4C6** [playwright-community/playwright-go#369]
Hi, i am facing multiples issues that make my program crash, it seems that i can't handle these errors.
When you see `restarting` it mean my browser is just closing and restarting.

Is there any way to handle theses errors instead of making the program panic?, thanks !

```
os: windows 11
cpu: i9 11900K
golang: 1.21.0
```

# Logs

## could not decode Json
```
2023/09/06 04:37:05 restarting
could not send message to server: Target closed
could not send message to server: Target closed
could not send message to server: Target closed
2023/09/06 04:37:05 could not decode json: read |0: file already closed
exit status 1
Appuyez sur une touche pour continuer... node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:61:25)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at PipeTransport.send (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\protocol\transport.js:51:21)
    at dispatcherConnection.onmessage (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\cli\driver.js:53:57)
    at DispatcherConnection._sendMessageToClient (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\server\dispatchers\dispatcher.js:188:10)
    at DispatcherConnection.sendCreate (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\server\dispatchers\dispatcher.js:161:10)
    at new Dispatcher (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\server\dispatchers\dispatcher.js:66:40)
    at new AndroidDispatcher (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\server\dispatchers\androidDispatcher.js:28:5)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

Node.js v18.16.0
```

## File already closed
```
could not send message to server: could not send message: write |1: file already closed
could not send message to server: could not send message: write |1: file already closed
2023/09/06 14:04:26 could not decode json: read |0: file already closed
could not send message to server: could not send message: write |1: file already closed
exit status 1
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:61:25)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at PipeTransport.send (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\protocol\transport.js:51:21)
    at dispatcherConnection.onmessage (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\cli\driver.js:53:57)
    at DispatcherConnection.dispatch (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\server\dispatchers\dispatcher.js:224:12)
    at transport.onmessage (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\cli\driver.js:52:57)
    at Immediate._onImmediate (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\protocol\transport.js:77:34)
    at process.processImmediate (node:internal/timers:476:21)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

Node.js v18.16.0
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:61:25)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at PipeTransport.send (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\protocol\transport.js:51:21)
    at dispatcherConnection.onmessage (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\cli\driver.js:53:57)
    at DispatcherConnection._sendMessageToClient (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\server\dispatchers\dispatcher.js:188:10)
    at DispatcherConnection.sendCreate (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\server\dispatchers\dispatcher.js:161:10)
    at new Dispatcher (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\server\dispatchers\dispatcher.js:66:40)
    at new AndroidDispatcher (C:\Users\arm\AppData\Local\ms-playwright-go\1.35.1\package\lib\server\dispatchers\androidDispatcher.js:28:5)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

Node.js v18.16.0
```

**Comment by canstand** [comment]
The error shown in the log occurs in nodejs, which means the error occurred on the [server side](https://github.com/microsoft/playwright). And the upstream version shown by the log is `v1.35.1`. Please update `playwright-go` to the latest version and test again.

**Comment by skye-z** [comment]
I'm having the same problem, it works fine on macOS, but on Win10 I get this error.

```shell
PS E:\Project\Workspace\Golang\auto-mooc> go run .\main.go
2023/09/19 22:58:42 could not decode json: invalid character 'v' looking for beginning of value
exit status 1
PS E:\Project\Workspace\Golang\auto-mooc> node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:61:25)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at PipeTransport.send (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\protocol\transport.js:51:21)
    at dispatcherConnection.onmessage (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\cli\driver.js:53:57)
    at DispatcherConnection._sendMessageToClient (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\server\dispatchers\dispatcher.js:189:10)
    at DispatcherConnection.sendCreate (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\server\dispatchers\dispatcher.js:162:10)
    at new Dispatcher (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\server\dispatchers\dispatcher.js:66:40)
    at new AndroidDispatcher (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\server\dispatchers\androidDispatcher.js:28:5)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

Node.js v18.17.0
```

**Comment by canstand** [comment]
> I'm having the same problem, it works fine on macOS, but on Win10 I get this error.
> 
> ```shell
> PS E:\Project\Workspace\Golang\auto-mooc> go run .\main.go
> 2023/09/19 22:58:42 could not decode json: invalid character 'v' looking for beginning of value
> exit status 1
> PS E:\Project\Workspace\Golang\auto-mooc> node:events:492
> ```

@skye-z It appears that the data received from the io pipe has an incorrect message format. Can you debug it and see what happened before the error occurred?

Set environment variable `DEBUGP=1` can print verbose log.

**Comment by skye-z** [comment]
@canstand Ok, I manually set the environment variable `os.Setenv("DEBUGP", "1")` in the code, and here is the new output

```shell
E:\Project\Workspace\Golang\auto-mooc>go run main.go
SEND>
{"guid":"","id":1,"metadata":{"apiName":"SerializeCallStack","isInternal":false,"location":{"file":"connection.go","line":138},"wallTime":371571000},"method":"initialize","params":{"sdkLanguage":"javascript"}}
2023/09/20 21:33:44 could not decode json: invalid character 'v' looking for beginning of value
exit status 1

E:\Project\Workspace\Golang\auto-mooc>node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:61:25)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at PipeTransport.send (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\protocol\transport.js:51:21)
    at dispatcherConnection.onmessage (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\cli\driver.js:53:57)
    at DispatcherConnection._sendMessageToClient (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\server\dispatchers\dispatcher.js:189:10)
    at DispatcherConnection.sendCreate (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\server\dispatchers\dispatcher.js:162:10)
    at new Dispatcher (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\server\dispatchers\dispatcher.js:66:40)
    at new AndroidDispatcher (C:\Users\Skay\AppData\Local\ms-playwright-go\1.37.1\package\lib\server\dispatchers\androidDispatcher.js:28:5)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

Node.js v18.17.0
```

The new output has more `SEND>`  JSON, which I've formatted below for ease of viewing.

```json
{
    "guid": "",
    "id": 1,
    "metadata": {
        "apiName": "SerializeCallStack",
        "isInternal": false,
        "location": {
            "file": "connection.go",
            "line": 138
        },
        "wallTime": 371571000
    },
    "method": "initialize",
    "params": {
        "sdkLanguage": "javascript"
    }
}
```

**Comment by canstand** [comment]
I suspect it's due to anti-virus software. Because playwright-go will run `~\AppData\Local\ms-playwright-go\1.37.1\playwright.cmd` and bind to its `stdin` and `stdout` to communicate. The log above shows that the first response format of playwright.cmd is incorrect, so it may have been intercepted.

**Comment by skye-z** [comment]
@canstand  Sorry, I don't have a standalone antivirus installed, I'm just using `Microsoft Defender` that comes with Windows 10.

I disable the real-time and tamper protection features of `Microsoft Defender`, but it still gives the same error message when it runs 😥

![image](https://github.com/playwright-community/playwright-go/assets/20382734/b025f7d1-5fa7-4374-9a8c-04c88b0a261f)

Considering that there might be a problem with `playwright`, I ran it manually, and it works fine.

**Comment by canstand** [comment]
Notice `Active code page: 65001` , maybe it’s because of this: https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window

**Comment by skye-z** [comment]
@canstand It's working fine now, thanks a lot. 👍

I added the `autorun` field to the registry, which automatically executes `chcp 65001` when Command starts, deleted it, and everything is back to normal. 😀
