### ISSUE TITLE
Randomly Crash Issue on Firefox

### ISSUE THREAD

**Issue by 0x0480** [playwright-community/playwright-go#427]
```
C:\Users\xxxxxxxxAppData\Local\ms-playwright-go\1.42.1\package\lib\server\firefox\ffNetworkManager.js:110
    response.setTransferSize(event.transferSize);
             ^

TypeError: Cannot read properties of null (reading 'setTransferSize')
    at FFNetworkManager._onRequestFinished (C:\Users\xxxxxxxx\AppData\Local\ms-playwright-go\1.42.1\package\lib\server\firefox\ffNetworkManager.js:110:14)
    at FFSession.emit (node:events:518:28)
    at C:\Users\xxxxxxxxAppData\Local\ms-playwright-go\1.42.1\package\lib\server\firefox\ffConnection.js:154:41

Node.js v20.11.0
```

It totally randomly occurs.

**Comment by 0x0480** [comment]
Also got `The process tried to write to a nonexistent pipe.` several times.

**Comment by mxschmitt** [comment]
Please re-open if you have a reproduction. Thank you.
